server:
  port: 8060



eureka:
  instance:
    hostname: ServiceDiscovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8060/eureka/

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true



spring:
    cloud:
      config:
        uri: http://localhost:8888
      bus:
        enabled: true
      stream:
        kafka:
          binder:
            zk-nodes: 127.0.0.1:2181
            brokers: 127.0.0.1:9092
    zipkin.baseUrl: http://localhost:9411
    sleuth.sampler.probability: 0.5
    profiles:
      active: default
    application:
      name: ServiceDiscovery



debug: true

#logging:
#    level.org.springframework: WARN
#    pattern.console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr
#    ([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
